# Generated by Django 4.0.5 on 2022-07-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentBestSellersListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('weeks_on_list', models.IntegerField()),
                ('publisher', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=256)),
                ('amazon_product_url', models.URLField(max_length=500)),
            ],
        ),
    ]
