# Generated by Django 4.0.5 on 2022-07-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentbestsellerslistitem',
            name='amazon_product_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='currentbestsellerslistitem',
            name='author',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='currentbestsellerslistitem',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='currentbestsellerslistitem',
            name='publisher',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='currentbestsellerslistitem',
            name='rank',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='currentbestsellerslistitem',
            name='title',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='currentbestsellerslistitem',
            name='weeks_on_list',
            field=models.IntegerField(blank=True),
        ),
    ]
